services:
    lexxpavlov_page.form.type.page:
        class: Lexxpavlov\PageBundle\Form\Type\PageType
        arguments: [ %lexxpavlov_page.content_type% ]
        tags:
            - { name: form.type, alias: lexxpavlov_page }